services:
  rbr-group-nginx:
    image: nginx:stable-alpine
    depends_on:
      - rbr-group-php
    networks:
      - rbr-group-project
    volumes:
      - ".docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - ".:/var/www/html"

  rbr-group-php:
    build:
      context: .docker/
    volumes:
      - ".:/var/www/html"
    networks:
      - rbr-group-project

  rbr-group-db:
    image: mysql:latest
    restart: unless-stopped
    depends_on:
      - rbr-group-php
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rbr_group_db
      MYSQL_USER: rbr_group
      MYSQL_PASSWORD: test4321
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - rbr-group-project

  rbr-group-mailer:
    image: schickling/mailcatcher
    networks:
      - rbr-group-project

networks:
  rbr-group-project:
    external: true

volumes:
  dbdata: ~
